apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-mahasiswa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mirwanasikin/kubernetes-app
    targetRevision: HEAD
    path: app/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: registry-mahasiswa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
